<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndicatorExplanationSeeder extends Seeder
{
    public function run(): void
    {
        $explanations = [
            'median_income' => [
                'description_short' => 'Median disposable income per person',
                'description_long' => 'The median annual disposable income (after taxes and transfers) for individuals aged 20+ living in this area. This captures the economic standing of the typical resident — not skewed by a few very high or very low earners.',
                'methodology_note' => 'Disposable income = earned income + capital income + transfers − taxes. Median = the middle value when all residents are ranked.',
                'national_context' => 'National median: ~248,000 SEK (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually, typically in Q1 for the previous year',
            ],
            'low_economic_standard_pct' => [
                'description_short' => 'Share of residents with low economic standard',
                'description_long' => 'The percentage of individuals whose household disposable income (adjusted for household size) falls below 60% of the national median. This is the EU standard definition of relative poverty risk.',
                'methodology_note' => 'Uses the modified OECD equivalence scale to adjust for household composition.',
                'national_context' => 'National average: ~14% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'employment_rate' => [
                'description_short' => 'Share of working-age residents who are employed',
                'description_long' => 'The percentage of residents aged 16–64 who are gainfully employed. High employment means stable household finances, which supports mortgage payments and local business activity.',
                'methodology_note' => 'Includes all forms of employment (full-time, part-time, self-employed). Measured in November each year.',
                'national_context' => 'National average: ~68% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'education_post_secondary_pct' => [
                'description_short' => 'Share of adults with university education',
                'description_long' => 'The percentage of residents aged 25–64 who have completed at least 3 years of post-secondary education (university degree or equivalent). A long-term predictor of area trajectory — highly educated populations attract employers and sustain higher incomes.',
                'methodology_note' => 'Based on the Swedish education register (Utbildningsregistret). Includes both Swedish and foreign degrees.',
                'national_context' => 'National average: ~29% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'education_below_secondary_pct' => [
                'description_short' => 'Share of adults without upper secondary education',
                'description_long' => 'The percentage of residents aged 25–64 who have not completed gymnasieutbildning (upper secondary school). A higher share indicates economic vulnerability — these residents have limited access to the modern labor market.',
                'methodology_note' => 'Includes individuals with only grundskola (9-year compulsory school) or less.',
                'national_context' => 'National average: ~12% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'foreign_background_pct' => [
                'description_short' => 'Share of residents with foreign background',
                'description_long' => 'The percentage of residents who are foreign-born or born in Sweden with two foreign-born parents. This indicator provides context but does not contribute to the composite score.',
                'methodology_note' => 'Uses SCB definition: foreign-born, or born in Sweden with two foreign-born parents.',
                'national_context' => 'National average: ~26% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'population' => [
                'description_short' => 'Total number of residents in the area',
                'description_long' => 'The total registered population in this DeSO area. This indicator provides context (area size) but does not contribute to the composite score.',
                'methodology_note' => 'Based on the Swedish population register as of December 31.',
                'national_context' => 'Average DeSO population: ~1,700 (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'rental_tenure_pct' => [
                'description_short' => 'Share of housing that is rental',
                'description_long' => 'The percentage of dwellings in the area that are rental apartments (hyresrätter). This indicator provides context on housing market composition but does not contribute to the composite score.',
                'methodology_note' => 'Includes all rental dwellings regardless of landlord type (municipal, private, cooperative).',
                'national_context' => 'National average: ~30% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Statistics Sweden (SCB)',
                'source_url' => 'https://www.scb.se',
                'update_frequency' => 'Published annually',
            ],
            'school_merit_value_avg' => [
                'description_short' => 'Average final grades of local primary schools',
                'description_long' => 'The average meritvärde (merit value) across all grundskolor physically located in this area, weighted by student count. Meritvärde is computed from students\' best 16 subject grades plus an optional 17th (moderna språk). It\'s the primary measure of school quality in Sweden.',
                'methodology_note' => 'Sum of 16 best grades (A=20, B=17.5 ... F=0) + optional 17th subject. Maximum possible: 340. Only grundskola (years F-9) included.',
                'national_context' => 'National average: ~228 points (2024). Top schools: 270+. Struggling schools: <180.',
                'data_vintage' => '2020/21',
                'source_name' => 'Swedish National Agency for Education (Skolverket)',
                'source_url' => 'https://www.skolverket.se',
                'update_frequency' => 'Published annually, typically in autumn',
            ],
            'school_goal_achievement_avg' => [
                'description_short' => 'Share of students achieving passing grades in all subjects',
                'description_long' => 'The average percentage of year-9 students who achieved at least grade E in all subjects, across all grundskolor in this area. This measures how well schools serve their entire student population, not just top performers.',
                'methodology_note' => 'Weighted average across schools in the area by student count.',
                'national_context' => 'National average: ~76% (2024)',
                'data_vintage' => '2020/21',
                'source_name' => 'Swedish National Agency for Education (Skolverket)',
                'source_url' => 'https://www.skolverket.se',
                'update_frequency' => 'Published annually',
            ],
            'school_teacher_certification_avg' => [
                'description_short' => 'Share of teachers with proper certification',
                'description_long' => 'The average percentage of teachers who are \'behöriga\' (certified/qualified) to teach their assigned subjects. Higher certification rates correlate with better student outcomes and indicate a school that can attract qualified staff.',
                'methodology_note' => 'Weighted average across schools in the area by student count.',
                'national_context' => 'National average: ~72% (2024)',
                'data_vintage' => '2020/21',
                'source_name' => 'Swedish National Agency for Education (Skolverket)',
                'source_url' => 'https://www.skolverket.se',
                'update_frequency' => 'Published annually',
            ],
            'crime_violent_rate' => [
                'description_short' => 'Estimated violent crimes per 100,000 residents',
                'description_long' => 'The estimated rate of violent crimes (assault, robbery, sexual offences) per 100,000 residents. Disaggregated from kommun-level data using demographic weighting. Lower rates indicate safer neighborhoods.',
                'methodology_note' => 'Kommun-level BRÅ data disaggregated to DeSO using income, employment, education, and vulnerability area weights.',
                'national_context' => 'National average: ~1,200/100k (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Swedish National Council for Crime Prevention (BRÅ)',
                'source_url' => 'https://www.bra.se',
                'update_frequency' => 'Published annually, typically in Q1',
            ],
            'crime_property_rate' => [
                'description_short' => 'Estimated property crimes per 100,000 residents',
                'description_long' => 'The estimated rate of property crimes (theft, burglary, criminal damage) per 100,000 residents. Disaggregated from kommun-level data using demographic weighting.',
                'methodology_note' => 'Kommun-level BRÅ data disaggregated to DeSO using income, employment, education, and vulnerability area weights.',
                'national_context' => 'National average: ~4,500/100k (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Swedish National Council for Crime Prevention (BRÅ)',
                'source_url' => 'https://www.bra.se',
                'update_frequency' => 'Published annually',
            ],
            'crime_total_rate' => [
                'description_short' => 'Estimated total reported crimes per 100,000 residents',
                'description_long' => 'The estimated total rate of all reported crimes per 100,000 residents. Includes all crime categories. Disaggregated from kommun-level data.',
                'methodology_note' => 'Kommun-level BRÅ data disaggregated to DeSO using demographic weighting.',
                'national_context' => 'National average: ~13,500/100k (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Swedish National Council for Crime Prevention (BRÅ)',
                'source_url' => 'https://www.bra.se',
                'update_frequency' => 'Published annually',
            ],
            'perceived_safety' => [
                'description_short' => 'Estimated share of residents who feel safe at night',
                'description_long' => 'The estimated percentage of residents who feel safe being outdoors alone late at night. Based on the National Safety Survey (NTU) at county level, disaggregated to DeSO using demographic weighting.',
                'methodology_note' => 'Län-level NTU survey data disaggregated to DeSO using inverted demographic weighting (safer areas get higher values).',
                'national_context' => 'National average: ~80% feel safe (2025)',
                'data_vintage' => '2025',
                'source_name' => 'Swedish National Council for Crime Prevention (BRÅ/NTU)',
                'source_url' => 'https://www.bra.se',
                'update_frequency' => 'Published annually',
            ],
            'vulnerability_flag' => [
                'description_short' => 'Police-designated vulnerable area classification',
                'description_long' => 'Whether this area overlaps with a police-designated vulnerable area (utsatt område). Areas classified as "särskilt utsatt" face the most severe challenges. This is based on the Swedish Police\'s assessment of organized crime and social conditions.',
                'methodology_note' => '0 = not in a vulnerable area, 1 = utsatt område, 2 = särskilt utsatt område. Based on ≥25% geographic overlap with police boundaries.',
                'national_context' => '275 of 6,160 DeSO areas overlap with vulnerable areas (2025)',
                'data_vintage' => '2025',
                'source_name' => 'Swedish Police Authority (Polismyndigheten)',
                'source_url' => 'https://polisen.se',
                'update_frequency' => 'Updated every 2 years',
            ],
            'debt_rate_pct' => [
                'description_short' => 'Estimated share of adults with enforcement debts',
                'description_long' => 'The estimated percentage of the adult population registered with debts at Kronofogden (the Swedish Enforcement Authority). A high rate indicates financial distress in the area.',
                'methodology_note' => 'Kommun-level Kolada data disaggregated to DeSO using income, employment, education, and vulnerability area weights.',
                'national_context' => 'National average: ~4.3% (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Kronofogden via Kolada',
                'source_url' => 'https://www.kolada.se',
                'update_frequency' => 'Published annually',
            ],
            'eviction_rate' => [
                'description_short' => 'Estimated evictions per 100,000 residents',
                'description_long' => 'The estimated rate of evictions (vräkningar) per 100,000 residents. Evictions are a strong signal of financial distress and housing instability in the area.',
                'methodology_note' => 'Kommun-level Kolada data disaggregated to DeSO using demographic weighting.',
                'national_context' => 'National average: ~20/100k (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Kronofogden via Kolada',
                'source_url' => 'https://www.kolada.se',
                'update_frequency' => 'Published annually',
            ],
            'median_debt_sek' => [
                'description_short' => 'Median debt per debtor at Kronofogden',
                'description_long' => 'The median debt amount (in SEK) among people registered at Kronofogden in this municipality. Shown at kommun level since individual medians cannot be disaggregated to smaller areas.',
                'methodology_note' => 'Kommun-level data only — the same value is shown for all areas within the same municipality. Median cannot be meaningfully disaggregated.',
                'national_context' => 'National median: ~120,000 SEK (2024)',
                'data_vintage' => '2024',
                'source_name' => 'Kronofogden via Kolada',
                'source_url' => 'https://www.kolada.se',
                'update_frequency' => 'Published annually',
            ],
            'grocery_density' => [
                'description_short' => 'Grocery stores accessible within the catchment area',
                'description_long' => 'The number of grocery stores per 1,000 residents within the catchment radius. Measures everyday shopping access — an important quality of life factor.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius from the area centroid, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Higher density in urban areas; rural areas may have zero nearby stores.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'healthcare_density' => [
                'description_short' => 'Healthcare facilities accessible within the catchment area',
                'description_long' => 'The number of healthcare facilities (clinics, pharmacies, hospitals) per 1,000 residents within the catchment radius. Measures access to medical services.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Urban areas typically have 5-10x more facilities per capita than rural areas.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'restaurant_density' => [
                'description_short' => 'Restaurants and cafés accessible within the catchment area',
                'description_long' => 'The number of restaurants and cafés per 1,000 residents within the catchment radius. A proxy for neighborhood vibrancy and amenity richness.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Varies widely: dense urban areas may have 10+ per 1,000; rural areas near zero.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'fitness_density' => [
                'description_short' => 'Gyms and sports facilities accessible within the catchment area',
                'description_long' => 'The number of gyms, sports centers, and fitness facilities per 1,000 residents within the catchment radius. Indicates access to health and recreation infrastructure.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Most areas have at least one facility within reach; density varies by urbanity.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'transit_stop_density' => [
                'description_short' => 'Public transport stops accessible within the catchment area',
                'description_long' => 'The number of public transport stops (bus, tram, metro, train) per 1,000 residents within the catchment radius. Strong transit access supports property values and daily convenience.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Stockholm inner city: 50+ stops/1,000; rural areas may have 1-2.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'gambling_density' => [
                'description_short' => 'Gambling venues within the catchment area',
                'description_long' => 'The number of gambling establishments per 1,000 residents within the catchment radius. Higher density of gambling venues is associated with socioeconomic challenges and lower area desirability.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Most areas have zero; concentrations appear in certain urban neighborhoods.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'pawn_shop_density' => [
                'description_short' => 'Pawn shops within the catchment area',
                'description_long' => 'The number of pawn shops per 1,000 residents within the catchment radius. Higher density can indicate financial distress in the surrounding area.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Very rare overall; most areas have zero.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
            'fast_food_density' => [
                'description_short' => 'Fast food restaurants within the catchment area',
                'description_long' => 'The number of late-night fast food restaurants per 1,000 residents within the catchment radius. High concentrations are weakly associated with lower neighborhood desirability.',
                'methodology_note' => 'Based on OpenStreetMap data. Counted within a catchment radius, normalized per 1,000 residents. Ranked within urbanity tier.',
                'national_context' => 'Varies by area type; concentrated near transport hubs and commercial zones.',
                'data_vintage' => '2025',
                'source_name' => 'OpenStreetMap (OSM)',
                'source_url' => 'https://www.openstreetmap.org',
                'update_frequency' => 'Monthly refresh from OSM',
            ],
        ];

        foreach ($explanations as $slug => $data) {
            DB::table('indicators')
                ->where('slug', $slug)
                ->update(array_merge($data, ['updated_at' => now()]));
        }
    }
}
