<?php

namespace Database\Seeders;

use App\Models\PoiCategory;
use Illuminate\Database\Seeder;

class PoiCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // ─── Positive: Existing ──────────────────────────────
            [
                'slug' => 'grocery',
                'name' => 'Grocery Stores',
                'indicator_slug' => 'grocery_density',
                'signal' => 'positive',
                'osm_tags' => ['shop' => ['supermarket', 'convenience', 'greengrocer']],
                'catchment_km' => 1.50,
                'display_tier' => 4,
                'icon' => 'shopping-cart',
                'color' => '#16a34a',
                'category_group' => 'shopping',
                'description' => 'Supermarkets, convenience stores, and greengrocers',
            ],
            [
                'slug' => 'healthcare',
                'name' => 'Healthcare Facilities',
                'indicator_slug' => 'healthcare_density',
                'signal' => 'positive',
                'osm_tags' => ['amenity' => ['hospital', 'clinic', 'doctors']],
                'catchment_km' => 3.00,
                'display_tier' => 2,
                'icon' => 'cross',
                'color' => '#16a34a',
                'category_group' => 'healthcare',
                'description' => 'Hospitals, clinics, and doctors',
            ],
            [
                'slug' => 'restaurant',
                'name' => 'Restaurants & Cafés',
                'indicator_slug' => 'restaurant_density',
                'signal' => 'positive',
                'osm_tags' => ['amenity' => ['restaurant', 'cafe']],
                'catchment_km' => 1.00,
                'display_tier' => 4,
                'icon' => 'coffee',
                'color' => '#16a34a',
                'category_group' => 'culture',
                'description' => 'Restaurants and cafés (not fast food)',
            ],
            [
                'slug' => 'fitness',
                'name' => 'Gyms & Fitness',
                'indicator_slug' => 'fitness_density',
                'signal' => 'positive',
                'osm_tags' => ['leisure' => ['fitness_centre', 'sports_centre'], 'sport' => ['padel']],
                'catchment_km' => 2.00,
                'display_tier' => 4,
                'icon' => 'dumbbell',
                'color' => '#16a34a',
                'category_group' => 'sports',
                'description' => 'Gyms, fitness centres, sports centres, padel courts',
            ],
            [
                'slug' => 'public_transport_stop',
                'name' => 'Public Transport Stops',
                'indicator_slug' => 'transit_stop_density',
                'signal' => 'positive',
                'osm_tags' => ['highway' => ['bus_stop'], 'railway' => ['station', 'halt', 'tram_stop']],
                'catchment_km' => 1.00,
                'display_tier' => 5,
                'icon' => 'bus',
                'color' => '#16a34a',
                'category_group' => 'infrastructure',
                'description' => 'Bus stops, train stations, tram stops',
            ],

            // ─── Positive: New ───────────────────────────────────
            [
                'slug' => 'pharmacy',
                'name' => 'Pharmacies',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['amenity' => ['pharmacy']],
                'catchment_km' => 1.00,
                'display_tier' => 4,
                'icon' => 'pill',
                'color' => '#16a34a',
                'category_group' => 'healthcare',
                'description' => 'Pharmacies and apotek',
            ],
            [
                'slug' => 'library',
                'name' => 'Libraries',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['amenity' => ['library']],
                'catchment_km' => 1.00,
                'display_tier' => 3,
                'icon' => 'book-open',
                'color' => '#16a34a',
                'category_group' => 'culture',
                'description' => 'Public libraries',
            ],
            [
                'slug' => 'park',
                'name' => 'Parks & Green Space',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['leisure' => ['park']],
                'catchment_km' => 0.50,
                'display_tier' => 3,
                'icon' => 'tree-pine',
                'color' => '#16a34a',
                'category_group' => 'nature',
                'description' => 'Parks and green spaces (>1 hectare for scoring)',
            ],
            [
                'slug' => 'nature_reserve',
                'name' => 'Nature Reserves',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['leisure' => ['nature_reserve']],
                'catchment_km' => 1.00,
                'display_tier' => 2,
                'icon' => 'trees',
                'color' => '#16a34a',
                'category_group' => 'nature',
                'description' => 'Nature reserves and protected areas',
            ],
            [
                'slug' => 'marina',
                'name' => 'Marinas & Boat Clubs',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['leisure' => ['marina']],
                'catchment_km' => 1.00,
                'display_tier' => 3,
                'icon' => 'sailboat',
                'color' => '#16a34a',
                'category_group' => 'nature',
                'description' => 'Marinas and boat clubs — affluence + waterfront lifestyle',
            ],
            [
                'slug' => 'swimming',
                'name' => 'Swimming Facilities',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['leisure' => ['swimming_pool', 'bathing_place']],
                'catchment_km' => 1.00,
                'display_tier' => 3,
                'icon' => 'waves',
                'color' => '#16a34a',
                'category_group' => 'sports',
                'description' => 'Swimming pools and bathing places',
            ],
            [
                'slug' => 'cultural_venue',
                'name' => 'Cultural Venues',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['tourism' => ['museum'], 'amenity' => ['theatre']],
                'catchment_km' => 1.00,
                'display_tier' => 3,
                'icon' => 'landmark',
                'color' => '#16a34a',
                'category_group' => 'culture',
                'description' => 'Museums, theatres, and cultural institutions',
            ],
            [
                'slug' => 'bookshop',
                'name' => 'Bookshops',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => ['shop' => ['books']],
                'catchment_km' => 0.50,
                'display_tier' => 4,
                'icon' => 'book',
                'color' => '#16a34a',
                'category_group' => 'culture',
                'description' => 'Bookshops — educated, high-cultural-capital demographic',
            ],
            [
                'slug' => 'school_grundskola',
                'name' => 'Primary Schools',
                'indicator_slug' => null,
                'signal' => 'positive',
                'osm_tags' => null,
                'catchment_km' => 2.00,
                'display_tier' => 3,
                'icon' => 'graduation-cap',
                'color' => '#2563eb',
                'category_group' => 'schools',
                'is_active' => false,
                'description' => 'Already handled by Skolverket indicators',
            ],
            [
                'slug' => 'premium_grocery',
                'name' => 'Premium Grocery',
                'indicator_slug' => 'premium_grocery_density',
                'signal' => 'positive',
                'osm_tags' => null,
                'google_types' => ['supermarket', 'grocery_or_supermarket'],
                'catchment_km' => 2.00,
                'display_tier' => 4,
                'icon' => 'shopping-bag',
                'color' => '#16a34a',
                'category_group' => 'shopping',
                'is_active' => false,
                'description' => 'Premium grocery stores (Google Places, future)',
            ],

            // ─── Negative: Existing ──────────────────────────────
            [
                'slug' => 'gambling',
                'name' => 'Gambling Venues',
                'indicator_slug' => 'gambling_density',
                'signal' => 'negative',
                'osm_tags' => ['shop' => ['bookmaker', 'lottery'], 'amenity' => ['gambling', 'casino']],
                'catchment_km' => 1.50,
                'display_tier' => 4,
                'icon' => 'dice-3',
                'color' => '#dc2626',
                'impact_radius_km' => 0.50,
                'category_group' => 'social',
                'description' => 'Bookmakers, lottery shops, casinos, gambling venues',
            ],
            [
                'slug' => 'pawn_shop',
                'name' => 'Pawn Shops',
                'indicator_slug' => 'pawn_shop_density',
                'signal' => 'negative',
                'osm_tags' => ['shop' => ['pawnbroker']],
                'catchment_km' => 1.50,
                'display_tier' => 4,
                'icon' => 'badge-dollar-sign',
                'color' => '#dc2626',
                'impact_radius_km' => 0.50,
                'category_group' => 'social',
                'description' => 'Pawn shops and pawnbrokers',
            ],
            [
                'slug' => 'fast_food_late',
                'name' => 'Late-Night Fast Food',
                'indicator_slug' => 'fast_food_density',
                'signal' => 'negative',
                'osm_tags' => ['amenity' => ['fast_food']],
                'catchment_km' => 1.00,
                'display_tier' => 5,
                'icon' => 'utensils',
                'color' => '#6b7280',
                'category_group' => 'social',
                'description' => 'Fast food restaurants',
            ],

            // ─── Negative: Environmental & Industrial ────────────
            [
                'slug' => 'wastewater_plant',
                'name' => 'Wastewater Treatment Plants',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['man_made' => ['wastewater_plant']],
                'catchment_km' => 2.00,
                'display_tier' => 2,
                'icon' => 'droplets',
                'color' => '#f97316',
                'impact_radius_km' => 2.00,
                'category_group' => 'industrial',
                'description' => 'Wastewater treatment plants — persistent sewage odor, 9-12% value reduction',
            ],
            [
                'slug' => 'landfill',
                'name' => 'Landfills & Waste Dumps',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['landuse' => ['landfill']],
                'catchment_km' => 3.00,
                'display_tier' => 2,
                'icon' => 'trash-2',
                'color' => '#f97316',
                'impact_radius_km' => 3.00,
                'category_group' => 'waste_water',
                'description' => 'Landfills and waste dumps — odor, vermin, truck traffic, groundwater risk',
            ],
            [
                'slug' => 'quarry',
                'name' => 'Quarries & Gravel Pits',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['landuse' => ['quarry']],
                'catchment_km' => 2.00,
                'display_tier' => 3,
                'icon' => 'mountain',
                'color' => '#f97316',
                'impact_radius_km' => 2.00,
                'category_group' => 'industrial',
                'description' => 'Quarries and gravel pits — blasting noise, dust, heavy truck traffic',
            ],
            [
                'slug' => 'prison',
                'name' => 'Prisons & Detention Centers',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['amenity' => ['prison']],
                'catchment_km' => 2.00,
                'display_tier' => 1,
                'icon' => 'lock',
                'color' => '#dc2626',
                'impact_radius_km' => 2.00,
                'category_group' => 'social',
                'description' => 'Prisons and detention centers — stigma, perceived safety',
            ],
            [
                'slug' => 'airport',
                'name' => 'Airports & Airfields',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['aeroway' => ['aerodrome']],
                'catchment_km' => 5.00,
                'display_tier' => 1,
                'icon' => 'plane',
                'color' => '#6b7280',
                'impact_radius_km' => 5.00,
                'category_group' => 'noise_sources',
                'description' => 'Airports and airfields — flight noise, especially approach/departure paths',
            ],
            [
                'slug' => 'wind_turbine',
                'name' => 'Wind Turbines',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => [
                    '_and' => [[['power', 'generator'], ['generator:source', 'wind']]],
                    'man_made' => ['windmill'],
                ],
                'catchment_km' => 1.00,
                'display_tier' => 3,
                'icon' => 'wind',
                'color' => '#eab308',
                'impact_radius_km' => 1.00,
                'category_group' => 'noise_sources',
                'description' => 'Wind turbines — noise, shadow flicker, visual impact',
            ],
            [
                'slug' => 'shooting_range',
                'name' => 'Shooting Ranges',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['sport' => ['shooting']],
                'catchment_km' => 1.50,
                'display_tier' => 3,
                'icon' => 'crosshair',
                'color' => '#f97316',
                'impact_radius_km' => 1.50,
                'category_group' => 'noise_sources',
                'description' => 'Shooting ranges — intermittent loud noise, lead contamination',
            ],
            [
                'slug' => 'paper_mill',
                'name' => 'Paper & Pulp Mills',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => [
                    '_and' => [[['man_made', 'works'], ['product', 'paper|pulp']]],
                    'industrial' => ['pulp_mill', 'paper_mill'],
                ],
                'catchment_km' => 5.00,
                'display_tier' => 2,
                'icon' => 'factory',
                'color' => '#f97316',
                'impact_radius_km' => 5.00,
                'category_group' => 'industrial',
                'description' => 'Paper & pulp mills — sulfur smell, carries 5-10 km downwind',
            ],
            [
                'slug' => 'waste_incinerator',
                'name' => 'Waste Incineration Plants',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => [
                    '_and' => [
                        [['power', 'plant'], ['plant:source', 'waste']],
                        [['man_made', 'works'], ['product', 'waste']],
                    ],
                ],
                'catchment_km' => 2.00,
                'display_tier' => 2,
                'icon' => 'flame',
                'color' => '#f97316',
                'impact_radius_km' => 2.00,
                'category_group' => 'industrial',
                'description' => 'Waste incineration and power plants — air quality, truck traffic',
            ],

            // ─── Negative: Social & Economic ─────────────────────
            [
                'slug' => 'nightclub',
                'name' => 'Nightclubs',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['amenity' => ['nightclub']],
                'catchment_km' => 0.50,
                'display_tier' => 4,
                'icon' => 'music',
                'color' => '#f97316',
                'impact_radius_km' => 0.50,
                'category_group' => 'social',
                'description' => 'Nightclubs — noise, weekend disturbance',
            ],
            [
                'slug' => 'sex_shop',
                'name' => 'Adult Entertainment',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['shop' => ['erotic'], 'amenity' => ['stripclub']],
                'catchment_km' => 0.50,
                'display_tier' => 5,
                'icon' => 'store',
                'color' => '#dc2626',
                'impact_radius_km' => 0.50,
                'category_group' => 'social',
                'description' => 'Sex shops and adult entertainment — nightlife/seediness signal',
            ],
            [
                'slug' => 'homeless_shelter',
                'name' => 'Homeless Shelters',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => [
                    '_and' => [[['social_facility', 'shelter'], ['social_facility:for', 'homeless']]],
                ],
                'catchment_km' => 0.50,
                'display_tier' => 4,
                'icon' => 'bed',
                'color' => '#f97316',
                'impact_radius_km' => 0.50,
                'category_group' => 'social',
                'description' => 'Homeless shelters — area distress indicator',
            ],

            // ─── Negative: Infrastructure Nuisances ──────────────
            [
                'slug' => 'recycling_station',
                'name' => 'Recycling Stations',
                'indicator_slug' => null,
                'signal' => 'negative',
                'osm_tags' => ['amenity' => ['recycling']],
                'catchment_km' => 0.20,
                'display_tier' => 5,
                'icon' => 'recycle',
                'color' => '#6b7280',
                'impact_radius_km' => 0.20,
                'category_group' => 'infrastructure',
                'description' => 'Recycling stations — noise from glass, weekend traffic',
            ],
        ];

        foreach ($categories as $data) {
            PoiCategory::query()->updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
