<?php

return [
    'safety' => [
        'label' => 'Trygghet & brottslighet',
        'label_short' => 'Trygghet',
        'icon' => 'shield-halved',
        'display_order' => 1,
        'score_layer' => 'area',
        'description' => 'Brottsstatistik, upplevd trygghet och polisens klassificering',
        'indicators' => [
            'crime_violent_rate',
            'crime_property_rate',
            'crime_total_rate',
            'vulnerability_flag',
            'perceived_safety',
            'gambling_density',
            'pawn_shop_density',
            'fast_food_density',
        ],
    ],
    'economy' => [
        'label' => 'Ekonomi & arbetsmarknad',
        'label_short' => 'Ekonomi',
        'icon' => 'chart-column',
        'display_order' => 2,
        'score_layer' => 'area',
        'description' => 'Inkomst, sysselsättning, skuldsättning och ekonomisk standard',
        'indicators' => [
            'median_income',
            'low_economic_standard_pct',
            'employment_rate',
            'debt_rate_pct',
            'eviction_rate',
            'median_debt_sek',
        ],
    ],
    'education' => [
        'label' => 'Utbildning & skolor',
        'label_short' => 'Utbildning',
        'icon' => 'graduation-cap',
        'display_order' => 3,
        'score_layer' => 'area',
        'description' => 'Utbildningsnivå i befolkningen och skolkvalitet',
        'indicators' => [
            'education_post_secondary_pct',
            'education_below_secondary_pct',
            'school_merit_value_avg',
            'school_goal_achievement_avg',
            'school_teacher_certification_avg',
        ],
    ],
    'environment' => [
        'label' => 'Miljö & service',
        'label_short' => 'Service',
        'icon' => 'tree',
        'display_order' => 4,
        'score_layer' => 'area',
        'description' => 'Grönområden, kollektivtrafik, mataffärer, sjukvård och restauranger',
        'indicators' => [
            'grocery_density',
            'healthcare_density',
            'restaurant_density',
            'fitness_density',
            'transit_stop_density',
        ],
    ],
    'proximity' => [
        'label' => 'Platsanalys',
        'label_short' => 'Plats',
        'icon' => 'location-dot',
        'display_order' => 5,
        'score_layer' => 'proximity',
        'description' => 'Avstånd till skolor, hållplatser, parker och service från din exakta adress',
        'indicators' => [
            'prox_school',
            'prox_green_space',
            'prox_transit',
            'prox_grocery',
            'prox_negative_poi',
            'prox_positive_poi',
        ],
    ],
    // 'contextual' is never displayed — internal use only
    // Contains: foreign_background_pct, population, rental_tenure_pct
];
